stage1
AMikhnyuk/grok_webix_again pull request #1
Opened 2021-11-05 09:44 UTC by AMikhnyuk

2021-11-08 06:43 UTC, tsemashko commented on client/sources/views/settings.js
> +		songsCollection.waitData.then(() => {
для чего ждать, пока придут данные, чтобы выполнить sync?

2021-11-08 06:43 UTC, tsemashko commented on client/sources/views/settings.js
> +		const form = this.$$("table:form");
эти вьюшки можно заранее на ините сохранить в this, потому что они у тебя еще в нескольких местах используются

2021-11-08 06:43 UTC, tsemashko commented on client/sources/views/top.js
> +		let header = {
почему не const?

2021-11-08 10:29 UTC, ekosiy requested changes

2021-11-08 10:29 UTC, ekosiy commented on client/config.js
> +	url : "http://localhost:3000"
в целом я бы рекомендовал через .env делать такие штуки и на фронте, как у тебя на бэке. На данном этапе норм и в таком виде, но если будет время - почитай обязательно

2021-11-08 10:29 UTC, ekosiy commented on client/sources/views/albums.js
> +						const M = 1000000
линтер у тебя работает?

2021-11-08 10:29 UTC, ekosiy commented on client/sources/views/settings.js
> +		this.group2.disable();
https://docs.webix.com/desktop__visibility.html тут может правильнее будет через batch попробовать? чтобы сразу прятать группами, раз много enable-disable светится?

2021-11-08 10:29 UTC, ekosiy commented on server/models/songs.model.js
> +import mydb from "../mydb.js"
ты же будешь везде mydb на sequilize менять?

2021-11-11 08:31 UTC, tsemashko reviewed
в этот ПР не добавляй новые фичи, потому что он и так слишком большой

2021-11-11 08:31 UTC, tsemashko commented on client/sources/views/albums.js
> +						${copiesnum / M > 1 ? `${copiesnum / M}M` : `${copiesnum / K}K`} `;
если написать 1000000 (миллион), то результат будет 1000K, поэтому логичнее оператор >= вместо >

2021-11-11 08:31 UTC, tsemashko commented on client/sources/views/albums.js
> +				image : image ? image : data.image});
такое можно написать проще - image || data.image

2021-11-11 08:31 UTC, tsemashko commented on client/sources/views/settings.js
> +								this.clearAll();
после того, как мы почистили формы, песни в таблице остаются, зачем? то есть уже не выбрана ни группа, ни альбом, но мы всё равно можем добавить/удалить песни в таблице

2021-11-11 08:31 UTC, tsemashko commented on client/sources/views/settings.js
> +						{
если и давать пользователю вводить номер песни, тогда наверное стоит двигать остальные по номерам, чтоб не было повторяющихся, и сортировать. либо просто запрещать добавлять номер к песне и дать возможность их менять местами через dnd

2021-11-11 08:31 UTC, tsemashko commented on client/sources/views/albums.js
> +						${copiesnum / M > 1 ? `${copiesnum / M}M` : `${copiesnum / K}K`} `;
еще поправь вариант, когда copiesnum пустой, чтоб не показывалось NaN

2021-11-12 07:50 UTC, tsemashko approved these changes

2021-11-15 07:04 UTC, ekosiy approved these changes

2021-11-15 07:23 UTC, ekosiy commented on server/seq.js
> +dotenv.config()
пока не забыл, сделай плз файлик .env.example, где будут перечислены поля для заполнения

2021-11-15 12:52 UTC, merged